spring:
  application:
    name: consumer-ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
    topic:
      notification: notification-single-topic

