spring:
  application:
    name: producer-ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.68.120:9093}
    topic:
      notification:
        name: notification-single-topic
        partitions: ${KAFKA_TOPIC_PARTITIONS:10}
        segment:
          bytes: 104857600 #100MB
        retention:
          bytes: 1073741824 #1GB